# Generated by Django 3.2.7 on 2021-10-17 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChromatographicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k1', models.DecimalField(decimal_places=4, max_digits=7)),
                ('k2', models.DecimalField(decimal_places=4, max_digits=7)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperature of column (°C)')),
                ('flow_rate', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Flow rate (ml/min)')),
                ('injected_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=3, verbose_name='Injected volume (µl)')),
                ('slug', models.SlugField(max_length=100, unique_for_date=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chromatographicmodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eluent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='First solvent / Second solvent')),
                ('description', models.TextField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=100, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_eluent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C18', 'C18-column'), ('C8', 'C8-column')], default='C18', max_length=20)),
                ('abbreviation', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=50, verbose_name='Dimensions, L×i.d.(mm×mm)')),
                ('particle_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Particle size (µm)')),
                ('pore_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pore size (C)')),
                ('pore_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pore volume (ml/g)')),
                ('surface_area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Surface area (m^2/g)')),
                ('carbon_loading', models.CharField(blank=True, max_length=50, verbose_name='Carbon loading(%)')),
                ('surface_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Surface coverage (µmol/m^2)')),
                ('bulk_density', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bulk density (g/ml)')),
                ('end_capping', models.CharField(blank=True, max_length=50)),
                ('silica', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(max_length=100, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_column', to=settings.AUTH_USER_MODEL)),
                ('eluents', models.ManyToManyField(through='Chromatography.ChromatographicModel', to='Chromatography.Eluent')),
            ],
        ),
        migrations.AddField(
            model_name='chromatographicmodel',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chromatography.column', to_field='abbreviation'),
        ),
        migrations.AddField(
            model_name='chromatographicmodel',
            name='eluent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chromatography.eluent', to_field='name'),
        ),
    ]
